# Generated by Django 4.1.2 on 2022-11-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credentials_file',
            field=models.FileField(default='default_credentials.json', upload_to='credentials'),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_file',
            field=models.FileField(default='default_token.json', upload_to='token'),
        ),
    ]
