# Generated by Django 4.1.2 on 2022-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_credentials_file_profile_token_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_image',
            field=models.ImageField(default=None, upload_to='auth_img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credentials_file',
            field=models.FileField(default=None, upload_to='credentials'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_file',
            field=models.FileField(default=None, upload_to='token'),
        ),
    ]
