# Generated by Django 4.1.2 on 2022-11-13 01:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(default=users.models.generate_key, editable=False, max_length=100),
        ),
    ]
