# Generated by Django 4.1.2 on 2022-11-13 02:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(default=users.models.generate_key, max_length=100),
        ),
    ]
