# Generated by Django 4.1.2 on 2022-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rootFolder',
            field=models.CharField(default='', max_length=100),
        ),
    ]
